const data =  [{
    id:'post1',
    catagory:'bollywood',
    img:'https://m.media-amazon.com/images/M/MV5BNTkyOGVjMGEtNmQzZi00NzFlLTlhOWQtODYyMDc2ZGJmYzFhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg',
    name:'3 Idiots',
    para:`3 Idiots (stylized as "3 idiots") is a 2009 Indian Hindi-language coming-of-age comedy-drama film written, edited and directed by Rajkumar Hirani, co-written by Abhijat Joshi and produced by Vidhu Vinod Chopra. Adapted loosely from Chetan Bhagat's novel Five Point Someone,[5] the film stars Aamir Khan, R. Madhavan and Sharman Joshi in the titular roles, marking their reunion three years after Rang De Basanti (2006), while Kareena Kapoor, Boman Irani and Omi Vaidya star in pivotal roles. Narrated through two parallel dramas, one in the present and the other set ten years in the past, the story follows the friendship of three students at an Indian engineering college and is a satire about the social pressures under the Indian education system.Produced by Chopra under the banner Vinod Chopra Films,[9][10] 3 Idiots incorporated real Indian inventions created by Remya Jose,[11] Mohammad Idris,[12] Jahangir Painter[13] and Sonam Wangchuk, the latter of whom also inspired Khan's characterUpon its release on December 25, 2009, 3 Idiots received widespread critical acclaim and commercial success and is considered to be among the greatest Bollywood films ever made;[15] it was also the highest-grossing film in its opening weekend in India, had the highest opening day collections for an Indian film up until that point, and also held the record for the highest net collections in the first week for a Hindi film. Eventually, it became one of the few Indian films at the time to become successful in East Asian markets such as China[16] and Japan,[17] eventually bringing its worldwide gross to ₹392 crore ($90 million)[a][18][19] — it was the highest-grossing Indian film ever at the time and the highest grossing Indian film of the 2000s. It is also the 17th highest grossing Indian film of all time.[20] The film also had a social impact on attitudes toward education in India,[21] as well as in other Asian countries such as China.[7]At the 57th National Film Awards, 3 Idiots won 3 National Film Awards, including Best Popular Film Providing Wholesome Entertainment. Additionally, the film received 11 nominations at the 55th Filmfare Awards, including Best Actor (Khan), Best Actress (Kapoor) and Best Supporting Actor (Madhavan and Joshi), and won a leading 6 awards (tying with Dev.D), including Best Film, Best Director (Hirani) and Best Supporting Actor (Irani). Overseas, it won the Grand Prize at Japan's Videoyasan Awards,[22][23][17] while it was nominated for Best Outstanding Foreign Language Film at the Japan Academy Awards[24][25] and Best Foreign Film at China's Beijing International Film Festival.[26]The film was remade in Tamil as Nanban (2012), which also received critical praise and commercial success.[27][28] A Mexican remake, 3 Idiotas, was also released in 2017.[29]`
  },
  {
    id:'post2',
    catagory:'bollywood',
    img:'https://upload.wikimedia.org/wikipedia/en/a/ae/Pinkmovieposter.jpg',
    name:'Pink',
    para:`Pink is a 2016 Indian Hindi-language legal thriller film directed by Aniruddha Roy Chowdhury and written by Shoojit Sircar, Ritesh Shah and Aniruddha Roy Chowdhury.[1] The film is produced by Rising Sun Films on a total budget of ₹30 crore, with screenplay by Shah and music composition by Shantanu Moitra and Anupam Roy.[4] Pink features an ensemble cast, which includes Taapsee Pannu, Kirti Kulhari, Andrea Tariang, Amitabh Bachchan, Angad Bedi, Tushar Pandey, Piyush Mishra, and Dhritiman ChatterjeePink was released in worldwide cinemas on 16 September 2016.[6] The film received widespread critical acclaim for the cast performances, execution, story, screenplay and direction.[2] Pink emerged as a surprising commercial success earning over ₹157.32 crore globally.[3] The film completed a 50-day run theatrically.[7]At the 64th National Film Awards, Pink won the category of Best Film on Other Social Issues.[8] Pink received 5 nominations at the 62nd Filmfare Awards, including Best Film, Best Actor (Bachchan) and Best Supporting Actress (Kulhari), and won Best Dialogue (Ritesh Shah).`
  },
  {
    id:'post3',
    catagory:'bollywood',
    img:'https://upload.wikimedia.org/wikipedia/en/d/d4/The_Kashmir_Files_poster.jpg',
    name:'The Kashmir Files',
    para:`The Kashmir Files is a 2022 Indian Hindi-language drama film[2] written and directed by Vivek Agnihotri.[6] The film presents a fictional storyline[1][7][a] centred around the 1990s exodus of Kashmiri Hindus from Indian-administered Kashmir.[9][10] It depicts the exodus and the events leading up to it[11] as a genocide,[12][13][14][15][16] a notion that is widely considered inaccurate by scholars.[17][18] The film claims that such facts were suppressed by a conspiracy of silence.[19] The Kashmir Files stars Mithun Chakraborty, Anupam Kher, Darshan Kumar, and Pallavi Joshi.[21] The plot follows a Kashmiri Hindu college student, raised by his exiled grandfather and shielded from the knowledge of the circumstances of the death of his parents. After his grandfather's death, the student, who had come to believe at college that the exodus was benign, becomes driven to uncover the facts of his family's deaths. The plot alternates between the student's quest in the present time, 2020, and his family's travails of thirty years before. The film was released in theatres on 11 March 2022.[6] It has been a commercial success,[1][22] seemingly benefitting from promotion by India's ruling Hindu nationalist Bharatiya Janata Party (BJP) and tax benefits.[23]The critical reception of the film was mixed,[1] with the cinematography and acting thought to be compelling,[27] but the storyline attracting criticism for attempting to recast established history[12][13][28] and propagating Islamophobia.[7][13][28][29][30] Supporters have praised the film for showing what they say is an overlooked aspect of Kashmir's history.[7] Indian Prime Minister Narendra Modi and several BJP ministers have praised the film.[28] Theatres across India have witnessed hate speech against Muslims, including incitement to violence.[31][32] As of 28 April 2022, the film, which cost approximately ₹15 crore (US$1.9 million)[33] to ₹25 crore (US$3.1 million)[4] to make, had grossed ₹340.92 crore (US$43 million) worldwide,[34] becoming the third highest-grossing Hindi film of 2022.`
  }
]

module.exports={data}