const data = [ {
    id:'post1',
    catagory:'travel',
    img:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Everest_North_Face_toward_Base_Camp_Tibet_Luca_Galuzzi_2006.jpg/408px-Everest_North_Face_toward_Base_Camp_Tibet_Luca_Galuzzi_2006.jpg',
    name:'Mount Everest',
    para:`Mount Everest (Nepali: सगरमाथा, romanized: Sagarmāthā; Tibetan: Chomolungma ཇོ་མོ་གླང་མ; Chinese: 珠穆朗玛峰; pinyin: Zhūmùlǎngmǎ Fēng) is Earth's highest mountain above sea level, located in the Mahalangur Himal sub-range of the Himalayas. The China–Nepal border runs across its summit point.[2] Its elevation (snow height) of 8,848.86 m (29,031.7 ft) was most recently established in 2020 by the Chinese and Nepali authoritiMount Everest attracts many climbers, including highly experienced mountaineers. There are two main climbing routes, one approaching the summit from the southeast in Nepal (known as the "standard route") and the other from the north in Tibet. While not posing substantial technical climbing challenges on the standard route, Everest presents dangers such as altitude sickness, weather, and wind, as well as hazards from avalanches and the Khumbu Icefall. As of 2019, over 300 people have died on Everest,[4] many of whose bodies remain on the mountain.[5]The first recorded efforts to reach Everest's summit were made by British mountaineers. As Nepal did not allow foreigners to enter the country at the time, the British made several attempts on the north ridge route from the Tibetan side. After the first reconnaissance expedition by the British in 1921 reached 7,000 m (22,970 ft) on the North Col, the 1922 expedition pushed the north ridge route up to 8,320 m (27,300 ft), marking the first time a human had climbed above 8,000 m (26,247 ft). The 1924 expedition resulted in one of the greatest mysteries on Everest to this day: George Mallory and Andrew Irvine made a final summit attempt on 8 June but never returned, sparking debate as to whether they were the first to reach the top. Tenzing Norgay and Edmund Hillary made the first documented ascent of Everest in 1953, using the southeast ridge route. Norgay had reached 8,595 m (28,199 ft) the previous year as a member of the 1952 Swiss expedition. The Chinese mountaineering team of Wang Fuzhou, Gonpo, and Qu Yinhua made the first reported ascent of the peak from the north ridge on 25 May 1960.[6]`
  },
  {
    id:'post2',
    catagory:'travel',
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHuf1vnA5saYhY2wJfOP_4hjE-CKyh3_xpzA&usqp=CAU",
    name:'Rajasthan',
    para:`Rajasthan (Hindi: [raːdʒəsˈtʰaːn] (listen); lit. 'Land of Kings')[9] is a state in northern India.[10][11][12] It covers 342,239 square kilometres (132,139 sq mi) or 10.4 per cent of India's total geographical area. It is the largest Indian state by area and the seventh largest by population. It is on India's northwestern side, where it comprises most of the wide and inhospitable Thar Desert (also known as the Great Indian Desert) and shares a border with the Pakistani provinces of Punjab to the northwest and Sindh to the west, along the Sutlej-Indus River valley. It is bordered by five other Indian states: Punjab to the north; Haryana and Uttar Pradesh to the northeast; Madhya Pradesh to the southeast; and Gujarat to the southwest. Its geographical location is 23.3 to 30.12 North latitude and 69.30 to 78.17 East longitude, with the Tropic of Cancer passing through its southernmosIts major features include the ruins of the Indus Valley civilisation at Kalibangan and Balathal, the Dilwara Temples, a Jain pilgrimage site at Rajasthan's only hill station, Mount Abu, in the ancient Aravalli mountain range and eastern Rajasthan, the Keoladeo National Park of Bharatpur, a World Heritage Site[13] known for its bird life. Rajasthan is also home to three national tiger reserves, the Ranthambore National Park in Sawai Madhopur, Sariska Tiger Reserve in Alwar and the Mukundra Hills Tiger Reserve in Kota.The state was formed on 30 March 1949 when Rajputana – the name adopted by the British Raj for its dependencies in the region[14] – was merged into the Dominion of India. Its capital and largest city is Jaipur. Other important cities are Jodhpur, Kota, Bikaner, Ajmer, Bharatpur and Udaipur. The economy of Rajasthan is the seventh-largest state economy in India with ₹10.20 lakh crore (US$130 billion) in gross domestic product and a per capita GDP of ₹118,000 (US$1,500).[3] Rajasthan ranks 29th among Indian states in human development index.[5]`
  },
  {
    id:'post3',
    catagory:'travel',
    img:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Havelock_Island%2C_Ethereal_mangrove_tree%2C_Andaman_Islands.jpg/1280px-Havelock_Island%2C_Ethereal_mangrove_tree%2C_Andaman_Islands.jpg',
    name:'Andaman Island',
    para:`The Andaman and Nicobar Islands is a union territory of India consisting of 572 islands, of which 37 are inhabited, at the junction of the Bay of Bengal and the Andaman Sea.[4] The territory is about 150 km (93 mi) north of Aceh in Indonesia and separated from Thailand and Myanmar by the Andaman Sea. It comprises two island groups, the Andaman Islands (partly) and the Nicobar Islands, separated by the 150 km (100 mile) wide Ten Degree Channel (on the 10°N parallel), with the Andaman islands to the north of this latitude, and the Nicobar islands to the south (or by 179 km; 111 miles). The Andaman Sea lies to the east and the Bay of Bengal to the west. The island chains are thought to be a submerged extension of the Arakan Mountainpm startThe territory's capital is the city of Port Blair. The total land area of the islands is approximately 8,249 km2 (3,185 sq mi). The territory is divided into three districts: the Nicobar District with Car Nicobar as its capital, the South Andaman district with Port Blair as its capital, and the North and Middle Andaman district with Mayabunder as its capital.npm startThe islands host the Andaman and Nicobar Command, the only tri-service geographical command of the Indian Armed Forces.[6]npm startThe Andaman Islands are also home to the Sentinelese people, an uncontacted tribe. The Sentinelese are considered to be the only people currently known to not have reached further than a Paleolithic level of technology;[7] however, this is disputed, as evidence of metalwork was found on their island.[8`
  }]

  module.exports={data}